DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;

DROP DATABASE IF EXISTS fifainfo;
CREATE DATABASE fifainfo;

SELECT * FROM fifainfo;
